### ISSUE TITLE
Hue service not working

### ISSUE THREAD

**Issue by JoaquinVillagra** [juliopez/Hadoop#1]
**Descripción del Bug**
El servicio de Hue no está disponible.
Luego de aplicar los comandos indicados, el servicio de cae. No persiste disponible por más de unos segundos.

**Para reproducir Bug**
1. Descargar repositorio
2. Ejecutar docker-compose up -d
3. Intentar acceder a servicio de Hue vía http://localhost:8888 (El servicio no resolverá la llamada web dado que estará abajo a los segundos).

**Comment by juliopez** [comment]
Hola @JoaquinVillagra ya tengo resuelto el problema con hue. Revisa este video https://youtu.be/Ck4sRPa0o24
